"""increase limit of title

Revision ID: 206287ac896a
Revises: b4244fd6af07
Create Date: 2025-11-18 17:46:57.117646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206287ac896a'
down_revision = 'b4244fd6af07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
